#!/bin/bash
# This renames files with spaces in them and replaces it with dashes

for file in *" "* ; do
	[[ -f ${file} ]] || continue
	echo "old file name: ${file}"	
	new_file="${file// /-}"
	mv "${file}" "${new_file}" && echo "new file name is:${new_file}"
done

	
